name: Control Push
on: [push]
jobs:

  qa:
  
    name: Check tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python@V1
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install pytest
        run: |
          pip install pytest
      - name: run tests  
        run: |
          python -m pytest --import-mode=append
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


