name: Control Push / Pull Request
on: push
jobs:

  qa:
  
    name: Check tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python@V1
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install pytest
        run: |
          pip install pytest
      - name: Install flake8
        run: |
          pip install flake8
      - name: run tests  
        run: |
          pytest
      - name: Run flake8
        uses: py-actions/flake8@v2



